parameters:
    knp_mailjet.event.factory.class:    Knp\Bundle\MailjetBundle\Event\EventFactory
    knp_mailjet.event.controller.class: Knp\Bundle\MailjetBundle\Controller\EventController

services:
    knp_mailjet.event.factory:
        class: %knp_mailjet.event.factory.class%

    knp_mailjet.event.controller:
        class: %knp_mailjet.event.controller.class%
        arguments:
            - "@knp_mailjet.event.factory"
            - "@event_dispatcher"
            - "%knp_mailjet.event.endpoint_token%"

#    # Example listener implementation
#    knp_mailjet.event.listener:
#        class:  Knp\Bundle\MailjetBundle\Event\Listener\EventListener
#        arguments:
#            - "@logger"
#        tags:
#            - { name: kernel.event_listener, event:  knp_mailjet.open,    method: onOpenEvent }
#            - { name: kernel.event_listener, event:  knp_mailjet.blocked, method: onBlockedEvent }
#            - { name: kernel.event_listener, event:  knp_mailjet.bounce,  method: onBounceEvent }
#            - { name: kernel.event_listener, event:  knp_mailjet.click,   method: onClickEvent }
#            - { name: kernel.event_listener, event:  knp_mailjet.spam,    method: onSpamEvent }
#            - { name: kernel.event_listener, event:  knp_mailjet.typofix, method: onTypofixEvent }
#            - { name: kernel.event_listener, event:  knp_mailjet.unsub,   method: onUnsubEvent }